### PR TITLE
first stab at improving set_union

### PR DESCRIPTION
**Pull request by WizardOfArc**
feedback is very welcome.

I'm thinking that instead of making the variadic case recursive, we _could_ put each of the provided collections in a vector and do something around that... although keeping track of which collection had the minimum value in order to advance might be too much calculation 🤔

### CODE REVIEW

**Comment by farziengineer** [comment]
Meanwhile, I'll look into what can be done with the varidac implementation.

**Comment by WizardOfArc** [comment]
one idea for doing union of variadic parameter of sets is to:

1. turn that into a vector of Collections (sets)
2. for each set in vector - sort them
3. declare a max_seen_so_far (auto?)
4. declare a vector of the above type (not sure how)
5. while at least one of the sets is non empty
6. take the first element of each and add to vector
7. sort this vector
8. for each element of this vector check if element == to max_seen_so_far 
9. if not, add to result and update max_seen_so_far accordingly
10. clear vector
11. do again with next element of each vector

**Comment by WizardOfArc** [comment]
@farziengineer sorry I didn't see the `hpp` file the first time around... I noticed that the signature in the .hpp file for `max` and `min` does not have `const` in it, but the `.cpp` file does.  I'm making my change accordingly....   I also noticed that the header file does not have declarations for intersect and union of arity 2 - does that need to be in there?

**Comment by farziengineer** [comment]
No problem 🙂. Actually you are right, some function declaration are not there in .hpp files.#12

**Comment by farziengineer** [comment]
Hi please configure your email and username locally, otherwise your contributions won't be shown.

**Comment by WizardOfArc** [comment]
@farziengineer how do I do that?  Set the config locally and then push again?

**Comment by farziengineer** [comment]
I do not think this would be a good idea. You can configure it now and your future commits would be shown on the profile. You can also search on Google if there is some workaround.

**Comment by WizardOfArc** [comment]
My friend helped me add my other committing email to my github account - so now it should be fine 😸

**Pull request merged**
