### PR TITLE
Change collection to container

### PR DESCRIPTION
**Pull request by juniormince**
renamed all of the Collection/related arguments

### CODE REVIEW

**Comment by farziengineer** [comment]
Hi, thanks for contribution but there are some more places in the same file where this needs to be changed. Please look into it.

**Comment by juniormince** [comment]
yeah just noticed that my b! looking into it now

**Comment by farziengineer** [comment]
No problem 🙂.

**Comment by juniormince** [comment]
was making a mess in the resolves and this one was behind so I made a new PR, see UPDATED. 🤘

**Pull request closed without merging**
