### PR TITLE
Updated README with intent of library

### PR DESCRIPTION
**Pull request by farziengineer**

### CODE REVIEW

**Comment by farziengineer** [comment]
Also not every function is a "manipulation".
what should we add in place of that.

**Comment by gubatron** [comment]
hmm, I guess it depends on what the function does.
Which reminds me that there's a few functions that should make the given containers `const` so we avoid mutability I was just fixing `_::set_union` and the function would sort the given containers in order to do its magic, I implemented a much simpler algorithm using set, but the point is that you don't want to alter the user's containers, I believe it's an unexpected effect that you want to unite 2 containers and then your original containers lost their previous sorting in favor of a canonical ordering algorithm.

**Comment by gubatron** [comment]
Do you know if when you pass the container by value a deep copy is made. I'll do some tests. it could be too expensive if full copies are made when the user passes a collection with MBs or GBs worth of data

**Comment by farziengineer** [comment]
Agree to your point. Deep copying is unacceptable. If we do not use deep copy, I think it is inevitable for the containers to retain their original state. The only was to not pass by value and not change the state would be to go for an O(n^2) which would entirely defeat the purpose :(

**Comment by farziengineer** [comment]
Woah, I totally misunderstood your point, but after looking at your branch, I think I got the idea.

**Pull request merged**
