### PR TITLE
Size function

### PR DESCRIPTION
**Pull request by Swati-007**
Implemented issue #14.
I.m new to open-source. Please tell me if anything is to be updated/corrected.

### CODE REVIEW

**Comment by Gotham13121997** [comment]
Thanks for contributing .You will also need to add the function signature in underscore.hpp and a test in tsting.cpp .

**Comment by Gotham13121997** [comment]
Signature will be like
```
template <typename Container>
typename Container::const_iterator size(Container container);
```

**Comment by farziengineer** [comment]
Thanks for the contribution @Swati-007 , but from next time please be sure to ask @Gotham13121997 or me tp assign the issue to you, before you start working.

**Comment by farziengineer** [comment]
Hi, please look into it @Swati-007 , so that we can merge it into master.

**Pull request closed without merging**
